{
  "swagger": "2.0",
  "basePath": "/gotapi/airConditioner",
  "info": {
    "title": "Air Conditioner Profile",
    "version": "2.0.0",
    "description": "スマートデバイスが持つエアーコンディショナー機器を操作する機能を提供するAPI。"
  },
  "consumes": [
    "application/x-www-form-urlencoded",
    "multipart/form-data"
  ],
  "paths": {
    "/": {
      "get": {
        "operationId": "airConditionerGet",
        "x-type": "one-shot",
        "summary": "スマートデバイスの電源状態を取得する。",
        "description": "スマートデバイスの電源がONかOFFであるかを返す。状態を取得できない場合はUNKNOWNを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの電源状態を返す。",
            "schema": {
              "$ref": "#/definitions/GetPowerStatusResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "powerstatus": "OFF"
              }
            }
          }
        }
      },
      "put": {
        "operationId": "airConditionerPut",
        "x-type": "one-shot",
        "summary": "スマートデバイスの電源を点ける。",
        "description": "スマートデバイスの電源をONにする。取得に失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "formData",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの電源をONにした結果を返す。取得に失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/PowerOnResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "airConditionerDelete",
        "x-type": "one-shot",
        "summary": "スマートデバイスの電源を消す。",
        "description": "スマートデバイスの電源をOFFにした結果を返す。取得に失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの電源をOFFの結果を返す。取得に失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/PowerOffResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        }
      }
    },
    "/powerSaving": {
      "get": {
        "operationId": "airConditionerPowerSavingGet",
        "x-type": "one-shot",
        "summary": "スマートデバイスの節電動作設定を取得する。",
        "description": "スマートデバイスの節電動作設定を取得する。取得に失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの節電動作設定を返す。取得に失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/GetPowerSavingResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "powersaving": "Normal"
              }
            }
          }
        }
      },
      "put": {
        "operationId": "airConditionerPowerSavingPut",
        "x-type": "one-shot",
        "summary": "スマートデバイスの節電動作設定を設定する。",
        "description": "スマートデバイスの節電動作設定を設定する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "formData",
            "required": true,
            "type": "string"
          },
          {
            "name": "powersaving",
            "description": "節電動作設定。<br> PowerSaving：節電動作中<br> Normal：通常動作中<br> Unknown：不明",
            "in": "formData",
            "required": true,
            "type": "string",
            "enum": [
              "PowerSaving",
              "Normal",
              "Unknown"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの節電動作設定を設定した結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/SetPowerSavingResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        }
      }
    },
    "/modeSetting": {
      "get": {
        "operationId": "airConditionerModeSettingGet",
        "x-type": "one-shot",
        "summary": "スマートデバイスの運転モード設定を取得する。",
        "description": "スマートデバイスの運転モード設定を取得する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの運転モード設定を取得結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/GetModeSettingResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "modesetting": "Automatic"
              }
            }
          }
        }
      },
      "put": {
        "operationId": "airConditionerModeSettingPut",
        "x-type": "one-shot",
        "summary": "スマートデバイスの運転モード設定を設定する。",
        "description": "スマートデバイスの運転モード設定を設定する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "formData",
            "required": true,
            "type": "string"
          },
          {
            "name": "modesetting",
            "description": "運転モード設定。<br> Automatic:自動<br> Cooling:冷房<br> Heating:暖房<br> Dehumidification:除湿<br> AirCirculator:送風<br> Other:その他",
            "in": "formData",
            "required": true,
            "type": "string",
            "enum": [
              "Automatic",
              "Cooling",
              "Heating",
              "Dehumidification",
              "AirCirculator",
              "Other"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの運転モード設定を設定結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/SetModeSettingResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        }
      }
    },
    "/roomTemperature": {
      "get": {
        "operationId": "airConditionerRoomTemperatureGet",
        "x-type": "one-shot",
        "summary": "スマートデバイスの室温計測値を取得する。",
        "description": "スマートデバイスの室温計測値を取得する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの室温計測値を取得結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/GetRoomTemperatureResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "roomtemperature": "25"
              }
            }
          }
        }
      }
    },
    "/temperature": {
      "get": {
        "operationId": "airConditionerTemperatureGet",
        "x-type": "one-shot",
        "summary": "スマートデバイスの温度設定値を取得する。",
        "description": "スマートデバイスの温度設定値を取得する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの温度設定値を取得結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/GetTemperatureResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "temperature": "20"
              }
            }
          }
        }
      },
      "put": {
        "operationId": "airConditionerTemperaturePut",
        "x-type": "one-shot",
        "summary": "スマートデバイスの温度設定値を設定する。",
        "description": "スマートデバイスの温度設定値を設定する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "formData",
            "required": true,
            "type": "string"
          },
          {
            "name": "temperature",
            "description": "温度設定値。<br> 0〜50 (℃)",
            "in": "formData",
            "required": true,
            "type": "integer",
            "minimum": 0,
            "maximum": 50
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの温度設定値を設定結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/SetTemperatureResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        }
      }
    },
    "/airFlow": {
      "get": {
        "operationId": "airConditionerAirFlowGet",
        "x-type": "one-shot",
        "summary": "スマートデバイスの風量設定値を取得する。",
        "description": "スマートデバイスの風量設定値を取得する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの風量設定値を取得結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/GetAirFlowResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "airflowauto": "true",
                "airflow": "0.0"
              }
            }
          }
        }
      },
      "put": {
        "operationId": "airConditionerAirFlowPut",
        "x-type": "one-shot",
        "summary": "スマートデバイスの風量設定値を設定する。",
        "description": "スマートデバイスの風量設定値を設定する。失敗した場合はエラーを返す。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "formData",
            "required": true,
            "type": "string"
          },
          {
            "name": "airflow",
            "description": "風量設定値。<br> 0.0〜1.0",
            "in": "formData",
            "required": false,
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          {
            "name": "airflowauto",
            "description": "風量自動モード設定。<br>\ntrue : 自動モード有効<br>\nfalse : 自動モード無効",
            "in": "formData",
            "required": false,
            "type": "boolean"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスの風量設定値を設定結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/SetAirFlowResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        }
      }
    },
    "/enlProperty": {
      "get": {
        "operationId": "airConditionerEnlPropertyGet",
        "x-type": "one-shot",
        "summary": "スマートデバイスがサポートしているECHONET Lite 機器オブジェクトプロパティの 設定内容を取得する（必須プロパティのみ）。",
        "description": "※enlproperty:ECHONET Lite Propertyのこと。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "epc",
            "description": "取得プロパティのEPC。<br> 取得するプロパティのEPCをカンマ区切りで列挙。10進または16進(0xXX)の値",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスがサポートしているECHONET Lite 機器オブジェクトプロパティの 設定内容を取得結果を返す。失敗した場合はエラーを返す。",
            "schema": {
              "$ref": "#/definitions/GetEnlPropertyResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "properties": [
                  {
                    "epc": "OperationStatus",
                    "value": "49"
                  },
                  {
                    "epc": "InstallationLocation",
                    "value": "0"
                  }
                ]
              }
            }
          }
        }
      },
      "put": {
        "operationId": "airConditionerEnlPropertyPut",
        "x-type": "one-shot",
        "summary": "スマートデバイスがサポートしているECHONET Lite 機器オブジェクトプロパティに 設定を行う（必須プロパティのみ）。",
        "description": "※enlproperty:ECHONET Lite Propertyのこと。",
        "parameters": [
          {
            "name": "serviceId",
            "description": "サービスID。取得対象スマートデバイス",
            "in": "formData",
            "required": true,
            "type": "string"
          },
          {
            "name": "epc",
            "description": "EPC。<br> ECHONET Property Code",
            "in": "formData",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "description": "EPCの設定値。",
            "in": "formData",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "スマートデバイスがサポートしているECHONET Lite 機器オブジェクトプロパティに 設定を行った結果を返す。失敗した場合は、エラーを返す。",
            "schema": {
              "$ref": "#/definitions/SetEnlPropertyResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "epc": "OperationStatus",
                "value": "49"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "GetPowerStatusResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "type": "object",
          "required": [
            "powerstatus"
          ],
          "properties": {
            "powerstatus": {
              "type": "string",
              "title": "電源状態",
              "description": "ON:電源オン<br> OFF:電源オフ<br> UNKNOWN:不明",
              "enum": [
                "ON",
                "OFF",
                "UNKNOWN"
              ]
            }
          }
        }
      ]
    },
    "PowerOnResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "PowerOffResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "GetPowerSavingResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "type": "object",
          "required": [
            "powersaving"
          ],
          "properties": {
            "powersaving": {
              "type": "string",
              "title": "節電動作設定",
              "description": "PowerSaving：節電動作中<br> Normal：通常動作中<br> Unknown：不明",
              "enum": [
                "PowerSaving",
                "Normal",
                "Unknown"
              ]
            }
          }
        }
      ]
    },
    "SetPowerSavingResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "GetModeSettingResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "type": "object",
          "required": [
            "modesetting"
          ],
          "properties": {
            "modesetting": {
              "type": "string",
              "title": "運転モード設定",
              "description": "Automatic:自動<br> Cooling:冷房<br> Heating:暖房<br> Dehumidification:除湿<br> AirCirculator:送風<br> Other:その他",
              "enum": [
                "Automatic",
                "Cooling",
                "Heating",
                "Dehumidification",
                "AirCirculator",
                "Other"
              ]
            }
          }
        }
      ]
    },
    "SetModeSettingResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "GetRoomTemperatureResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "type": "object",
          "required": [
            "roomtemperature"
          ],
          "properties": {
            "roomtemperature": {
              "type": "integer",
              "title": "室内温度計測値",
              "description": "-127〜125 (℃)"
            }
          }
        }
      ]
    },
    "GetTemperatureResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "type": "object",
          "required": [
            "temperature"
          ],
          "properties": {
            "temperature": {
              "type": "integer",
              "title": "温度設定値",
              "description": "0〜50 (℃)"
            }
          }
        }
      ]
    },
    "SetTemperatureResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "GetAirFlowResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "type": "object",
          "required": [
            "airflow"
          ],
          "properties": {
            "airflow": {
              "type": "number",
              "title": "風量設定値",
              "description": "0.0〜1.0"
            },
            "airflowauto": {
              "type": "boolean",
              "title": "風量自動モード設定",
              "description": "true:自動モード有効<br> false:自動モード無効<br> ※(注1)風量自動モード設定をtrue設定した時のみ省略可。<br> ※(注2) 省略時及びfalse設定時は、「風量設定値」が反映される。"
            }
          }
        }
      ]
    },
    "SetAirFlowResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "GetEnlPropertyResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "type": "object",
          "required": [
            "properties"
          ],
          "properties": {
            "properties": {
              "type": "array",
              "title": "EPCのリスト",
              "description": "指定されたEPCの配列。",
              "items": {
                "type": "object",
                "required": [
                  "epc",
                  "value"
                ],
                "properties": {
                  "epc": {
                    "type": "string",
                    "title": "EPC",
                    "description": "ECHONET Property Code"
                  },
                  "value": {
                    "type": "string",
                    "title": "設定値",
                    "description": "ECHONET Property Codeの設定値。"
                  }
                }
              }
            }
          }
        }
      ]
    },
    "SetEnlPropertyResponse": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "CommonResponse": {
      "type": "object",
      "required": [
        "result",
        "product",
        "version"
      ],
      "properties": {
        "result": {
          "type": "integer",
          "title": "処理結果",
          "description": "0: 正常応答<br> 0以外: 異常応答"
        },
        "product": {
          "type": "string",
          "title": "システム名",
          "description": "DeviceConnectシステムの名前。"
        },
        "version": {
          "type": "string",
          "title": "システムバージョン",
          "description": "DeviceConnectシステムのバージョン名。"
        },
        "hmac": {
          "type": "string",
          "title": "署名",
          "description": "レスポンスに対する署名。 アプリケーション側から事前にHMACキーを共有されていた場合は必須。"
        }
      }
    }
  }
}
