{
    "swagger": "2.0",
    "info": {
        "title": "DeviceOrientation Profile",
        "version": "2.0.0",
        "description": "スマートデバイスの加速度センサー機能を提供するAPI。"
    },
    "consumes": [
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "paths": {
        "/onDeviceOrientation": {
            "get": {
                "x-type": "one-shot",
                "summary": "スマートデバイスが検知した加速度や重力込みの加速度（加速度センサー）、そして角速度（ジャイロセンサー）を通知イベントを取得する。",
                "description": "スマートデバイスでサポートしていないパラメータがある場合には、そのパラメータを省略する。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/DeviceOrientationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "orientation": {
                                    "acceleration": {
                                        "x": 0.12345678901234567,
                                        "y": 0.98765432109876543,
                                        "z": 0.24680135792468013
                                    },
                                    "rotationRate": {
                                        "alpha": -0.24680135792468013,
                                        "beta": 0.12345678901234567,
                                        "gamma": -0.98765432109876543
                                    },
                                    "accelerationIncludingGravity": {
                                        "x": 0.24680135792468013,
                                        "y": 0.12345678901234567,
                                        "z": 9.87654321098
                                    },
                                    "interval": 0
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "x-type": "event",
                "summary": "スマートデバイスが検知した加速度や重力込みの加速度（加速度センサー）、そして角速度（ジャイロセンサー）の通知イベントを開始する。",
                "description": "スマートデバイスでサポートしていないパラメータがある場合には、そのパラメータを省略する。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interval",
                        "in": "formData",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "value": "Register OnDeviceOrientation event"
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/DeviceOrientationEvent"
                    },
                    "examples": {
                        "application/json": {
                            "serviceId": "Host.dummyId.localhost.deviceconnect.org",
                            "profile": "",
                            "attribute": "",
                            "orientation": {
                                "acceleration": {
                                    "x": 0.12345678901234567,
                                    "y": 0.98765432109876543,
                                    "z": 0.24680135792468013
                                },
                                "rotationRate": {
                                    "alpha": -0.24680135792468013,
                                    "beta": 0.12345678901234567,
                                    "gamma": -0.98765432109876543
                                },
                                "accelerationIncludingGravity": {
                                    "x": 0.24680135792468013,
                                    "y": 0.12345678901234567,
                                    "z": 9.87654321098
                                },
                                "interval": 0
                            }
                        }
                    }
                }
            },
            "delete": {
                "x-type": "event",
                "summary": "スマートデバイスが検知した加速度や重力込みの加速度（加速度センサー）、そして角速度（ジャイロセンサー）の通知イベントを停止する。",
                "description": "スマートデバイスでサポートしていないパラメータがある場合には、そのパラメータを省略する。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "value": "Unregister OnDeviceOrientation event"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
         "DeviceOrientationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/DeviceOrientationInfo"
                }
            ]
        },
        "DeviceOrientationEvent": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                },
                {
                    "$ref": "#/definitions/DeviceOrientationInfo"
                }
            ]
        },
        "DeviceOrientationInfo": {
            "type": "object",
            "required": [
                "orientation"
            ],
            "properties": {
                "orientation": {
                    "type": "object",
                    "required": [
                        "interval"
                    ],
                    "properties": {
                        "interval": {
                            "type": "integer",
                            "format": "int64",
                            "title": "インターバル",
                            "description": "インターバル (単位: ミリ秒)"
                        },
                        "acceleration": {
                            "type": "object",
                            "title": "加速度",
                            "description": "加速度のオブジェクト。",
                            "required": [
                                "x",
                                "y",
                                "z"
                            ],
                            "properties": {
                                "x": {
                                    "type": "number",
                                    "title": "x軸成分",
                                    "description": "x軸方向への加速度（m/s2）。"
                                },
                                "y": {
                                    "type": "number",
                                    "title": "y軸成分",
                                    "description": "y軸方向への加速度（m/s2）。"
                                },
                                "z": {
                                    "type": "number",
                                    "title": "z軸成分",
                                    "description": "z軸方向への加速度（m/s2）。"
                                }
                            }
                        },
                        "accelerationIncludingGravity": {
                            "type": "object",
                            "title": "重力込みの加速度",
                            "description": "重力込みの加速度のオブジェクト。",
                            "required": [
                                "x",
                                "y",
                                "z"
                            ],
                            "properties": {
                                "x": {
                                    "type": "number",
                                    "title": "x軸成分",
                                    "description": "x軸方向への重力込みの加速度（m/s2）。"
                                },
                                "y": {
                                    "type": "number",
                                    "title": "y軸成分",
                                    "description": "y軸方向への重力込みの加速度（m/s2）。"
                                },
                                "z": {
                                    "type": "number",
                                    "title": "z軸成分",
                                    "description": "z軸方向への重力込みの加速度（m/s2）。"
                                }
                            }
                        },
                        "rotationRate": {
                            "type": "object",
                            "title": "角速度",
                            "description": "角速度のオブジェクト。",
                            "required": [
                                "alpha",
                                "beta",
                                "gamma"
                            ],
                            "properties": {
                                "alpha": {
                                    "type": "number",
                                    "title": "z軸回り成分",
                                    "description": "z軸回りの角速度(degree/s)。"
                                },
                                "beta": {
                                    "type": "number",
                                    "title": "x軸回り成分",
                                    "description": "x軸回りの角速度(degree/s)。"
                                },
                                "gamma": {
                                    "type": "number",
                                    "title": "y軸回り成分",
                                    "description": "y軸回りの角速度(degree/s)。"
                                }
                            }
                        }
                    }
                }
            }
        },
        "CommonResponse": {
            "type": "object",
            "required": [
                "result",
                "product",
                "version"
            ],
            "properties": {
                "result": {
                    "type": "integer",
                    "description": "0:正常応答<br>0以外:異常応答"
                },
                "product": {
                    "type": "string",
                    "description": "DeviceConnectシステムの名前。"
                },
                "version": {
                    "type": "string",
                    "description": "DeviceConnectシステムのバージョン名。"
                },
                "hmac": {
                    "type": "string",
                    "description": "レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。"
                }
            }
        },
        "EventRegistrationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "EventUnregistrationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "CommonEvent": {
            "type": "object",
            "required": [
                "serviceId",
                "profile",
                "interface",
                "attribute"
            ],
            "properties": {
                "serviceId": {
                    "type": "string",
                    "description": "0:正常応答<br>0以外:異常応答"
                },
                "profile": {
                    "type": "string",
                    "description": "プロファイル名。"
                },
                "interface": {
                    "type": "string",
                    "description": "インターフェース名。"
                },
                "attribute": {
                    "type": "string",
                    "description": "アトリビュート名。"
                }
            }
        }
    }
}