{
    "swagger": "2.0",
    "basePath": "/gotapi/notification",
    "info": {
        "title": "Notification Profile",
        "version": "2.0.0",
        "description": "スマートデバイスのノーティフィケーションを操作する機能。"
    },
    "consumes": [
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "paths": {
        "/notify": {
            "post": {
                "operationId": "notificationNotifyPost",
                "x-type": "one-shot",
                "summary": "スマートデバイスにノーティフィケーションの表示要求をする。",
                "description": "ノーティフィケーションの表示要求の到達成否を応答として返却し、ノーティフィケーションの表示完了を待って応答をするわけではない。ノーティフィケーションの表示方法は表示要求を受けたスマートデバイスに依存する。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "type",
                        "description": "通知タイプ。通知のタイプを識別する。<br>0: 音声通話着信<br>1: メール着信<br>2: SMS着信<br>3: イベント",
                        "in": "formData",
                        "required": true,
                        "type": "integer",
                        "enum": [0, 1, 2, 3]
                    },
                    {
                        "name": "dir",
                        "description": "向き。メッセージの文字の向き。<br>auto: 自動<br>rtl: 右から左<br>ltr: 左から右",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "enum": ["auto", "ltr", "rtl"]
                    },
                    {
                        "name": "lang",
                        "description": "言語。メッセージの言語。 ref. BCP47",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "body",
                        "description": "表示させる文字列。",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "tag",
                        "description": "タグ。任意タグ文字列 カンマ(,)区切りで任意個数指定。",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "uri",
                        "description": "アイコン。アイコンファイルのURI。",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/SendNotificationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "notificationId": 123456
                            }
                        }
                    }
                }
            },
            "delete": {
                "operationId": "notificationNotifyDelete",
                "x-type": "one-shot",
                "summary": "スマートデバイスにノーティフィケーションの消去要求をする。",
                "description": "ノーティフィケーションの消去要求の到達成否を応答として返却し、ノーティフィケーションの消去完了を待って応答をするわけではない。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "notificationId",
                        "description": "通知ID。ユニークな文字列。",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/DeleteNotificationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/onClick": {
            "get": {
                "operationId": "notificationOnClickGet",
                "x-type": "one-shot",
                "summary": "スマートデバイスのノーティフィケーションがクリックされたことを通知するイベントを取得する。",
                "description": "スマートデバイスでノーティフィケーションがクリック(タップ)された時にイベントが発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/ClickNotificationResponse"
                        },
                        "examples": {
                          "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "notificationId": 123456
                          }
                        }
                    }
                }
            },
            "put": {
                "operationId": "notificationOnClickPut",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーションがクリックされたことを通知するイベントを開始する。",
                "description": "スマートデバイスでノーティフィケーションがクリック(タップ)された時にイベントが発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interval",
                        "description": "デバイスプラグインがイベントを送信する間隔。",
                        "in": "formData",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/ClickNotificationEvent"
                    },
                    "examples": {
                        "application/json": {
                            "serviceId": "Host.dummyId.localhost.deviceconnect.org",
                            "profile": "notification",
                            "attribute": "onclick",
                            "notificationId": 123456
                        }
                    }
                }
            },
            "delete": {
                "operationId": "notificationOnClickDelete",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーションがクリックされたことを通知するイベントを停止する。",
                "description": "スマートデバイスでノーティフィケーションがクリック(タップ)された時にイベントが発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/onShow": {
            "get": {
                "operationId": "notificationOnShowGet",
                "x-type": "one-shot",
                "summary": "スマートデバイスのノーティフィケーションが表示されたことを通知するイベントを取得する。",
                "description": "スマートデバイスでノーティフィケーションが表示された時にイベントが発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/ShowNotificationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "notificationId": 123456
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "notificationOnShowPut",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーションが表示されたことを通知するイベントを開始する。",
                "description": "スマートデバイスでノーティフィケーションが表示された時にイベントが発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interval",
                        "description": "デバイスプラグインがイベントを送信する間隔。",
                        "in": "formData",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/ShowNotificationEvent"
                    },
                    "examples": {
                        "application/json": {
                            "serviceId": "Host.dummyId.localhost.deviceconnect.org",
                            "profile": "notification",
                            "attribute": "onshow",
                            "notificationId": 123456
                        }
                    }
                }
            },
            "delete": {
                "operationId": "notificationOnShowDelete",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーションが表示されたことを通知するイベントを停止する。",
                "description": "スマートデバイスでノーティフィケーションが表示された時にイベントが発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/onClose": {
            "get": {
                "operationId": "notificationOnCloseGet",
                "x-type": "one-shot",
                "summary": "スマートデバイスのノーティフィケーションが消去されたことを通知するイベントを取得する。",
                "description": "ユーザ操作による消去、プログラムからの消去要求による消去のいずれのイベントでもイベントは発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/CloseNotificationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "notificationId": 123456
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "notificationOnClosePut",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーションが消去されたことを通知するイベントを開始する。",
                "description": "ユーザ操作による消去、プログラムからの消去要求による消去のいずれのイベントでもイベントは発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interval",
                        "description": "デバイスプラグインがイベントを送信する間隔。",
                        "in": "formData",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/CloseNotificationEvent"
                    },
                    "examples": {
                        "application/json": {
                            "serviceId": "Host.dummyId.localhost.deviceconnect.org",
                            "profile": "notification",
                            "attribute": "onclose",
                            "notificationId": 123456
                        }
                    }
                }
            },
            "delete": {
                "operationId": "notificationOnCloseDelete",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーションが消去されたことを通知するイベントを停止する。",
                "description": "ユーザ操作による消去、プログラムからの消去要求による消去のいずれのイベントでもイベントは発行される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/onError": {
            "get": {
                "operationId": "notificationOnErrorGet",
                "x-type": "one-shot",
                "summary": "スマートデバイスのノーティフィケーション操作でエラーが発生したことを通知するイベントを取得する。",
                "description": "スマートデバイスでノーティフィケーション操作でエラーが発生した時にイベントが発行される。表示要求に対する表示失敗のエラー、非表示要求に対する消去失敗のエラーなどが通知される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/ErrorNotificationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "notificationId": 123456
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "notificationOnErrorPut",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーション操作でエラーが発生したことを通知するイベントを開始する。",
                "description": "スマートデバイスでノーティフィケーション操作でエラーが発生した時にイベントが発行される。表示要求に対する表示失敗のエラー、非表示要求に対する消去失敗のエラーなどが通知される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interval",
                        "description": "デバイスプラグインがイベントを送信する間隔。",
                        "in": "formData",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/ErrorNotificationEvent"
                    },
                    "examples": {
                        "application/json": {
                            "serviceId": "Host.dummyId.localhost.deviceconnect.org",
                            "profile": "notification",
                            "attribute": "onerror",
                            "notificationId": 123456
                        }
                    }
                }
            },
            "delete": {
                "operationId": "notificationOnErrorDelete",
                "x-type": "event",
                "summary": "スマートデバイスのノーティフィケーション操作でエラーが発生したことを通知するイベントを停止する。",
                "description": "スマートデバイスでノーティフィケーション操作でエラーが発生した時にイベントが発行される。表示要求に対する表示失敗のエラー、非表示要求に対する消去失敗のエラーなどが通知される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        }
    },

    "definitions": {
        "SendNotificationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                  "type": "object",
                  "required": [
                      "notificationId"
                  ],
                  "properties": {
                      "notificationId": {
                              "type": "string",
                              "title": "ノーティフィケーションID",
                              "description": "ユニークな文字列。"
                      }
                  }
                }
            ]
        },
        "DeleteNotificationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
         "ClickNotificationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
        "ClickNotificationEvent": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
         "ShowNotificationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
        "ShowNotificationEvent": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
         "CloseNotificationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
        "CloseNotificationEvent": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
         "ErrorNotificationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
        "ErrorNotificationEvent": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                },
                {
                    "$ref": "#/definitions/NotificationInfo"
                }
            ]
        },
        "NotificationInfo": {
            "type": "object",
            "required": [
                "notificationId"
            ],
            "properties": {
                "notificationId": {
                    "type": "string",
                    "title": "ノーティフィケーションID",
                    "description": "ノーティフィケーションを識別するID。"
                }
            }
        },
        "EventRegistrationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "EventUnregistrationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "CommonResponse": {
            "type": "object",
            "required": [
                "result",
                "product",
                "version"
            ],
            "properties": {
                "result": {
                    "type": "integer",
                    "title": "処理結果",
                    "description": "0:正常応答<br>0以外:異常応答"
                },
                "product": {
                    "type": "string",
                    "title": "システム名",
                    "description": "DeviceConnectシステムの名前。"
                },
                "version": {
                    "type": "string",
                    "title": "システムバージョン",
                    "description": "DeviceConnectシステムのバージョン名。"
                },
                "hmac": {
                    "type": "string",
                    "title": "署名",
                    "description": "レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。"
                }
            }
        },
        "CommonEvent": {
            "type": "object",
            "required": [
                "serviceId",
                "profile",
                "interface",
                "attribute"
            ],
            "properties": {
                "serviceId": {
                    "type": "string",
                    "title": "サービスID",
                    "description": "イベントを送信したサービスのID"
                },
                "profile": {
                    "type": "string",
                    "title": "プロファイル名",
                    "description": "プロファイル名。"
                },
                "interface": {
                    "type": "string",
                    "title": "インターフェース名",
                    "description": "インターフェース名。"
                },
                "attribute": {
                    "type": "string",
                    "title": "アトリビュート名",
                    "description": "アトリビュート名。"
                }
            }
        }
    }
}
