{
    "swagger": "2.0",
    "basePath": "/gotapi/powerMeter",
    "info": {
        "title": "Power Meter Profile",
        "version": "2.0.0",
        "description": "スマートデバイスが計測した電力を取得する機能を提供するAPI。"
    },
    "consumes": [
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "paths": {
        "/": {
            "get": {
                "x-type": "one-shot",
                "summary": "スマートデバイスの電源状態を取得する。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/PowerStateResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "powerstate": "OFF"
                            }
                        }
                    }
                }
            },
            "put": {
                "x-type": "one-shot",
                "summary": "スマートデバイスの電源を付ける。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/PowerControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            },
            "delete": {
                "x-type": "one-shot",
                "summary": "スマートデバイスの電源を消す。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/PowerControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/integratedPower": {
            "get": {
                "x-type": "one-shot",
                "summary": "スマートデバイスが計測した積算電力量を取得する。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "date",
                        "description": "取得日付。RFC 3339 例: 2014-01-01T00:00:00+0900",
                        "in": "query",
                        "required": false,
                        "type": "string",
                        "format": "date-time"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/IntegratedPowerValueResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "integratedpowervalue": [
                                    0,
                                    1,
                                    2,
                                    4,
                                    8,
                                    16,
                                    32,
                                    64,
                                    128,
                                    256,
                                    512,
                                    1024,
                                    2048,
                                    4096,
                                    8192,
                                    16384,
                                    32768,
                                    65536,
                                    131072,
                                    262144,
                                    524288,
                                    1048576,
                                    2097152,
                                    4194304
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/instantaneousPower": {
            "get": {
                "x-type": "one-shot",
                "summary": "スマートデバイスが計測した瞬間電力量を取得する。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象スマートデバイス",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/InstantaneousPowerValueResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "instantaneouspowervalue": 38.4
                            }
                        }
                    }
                }
            }
        }
    },

    "definitions": {
        "PowerState": {
            "type": "object",
            "required": [
                "powerstate"
            ],
            "properties": {
                "powerstate": {
                    "type": "string",
                    "title": "電源状態",
                    "description": "電源状態を示す文字列。",
                    "enum": ["ON", "OFF", "UNKNOWN"]
                }
            }
        },
        "PowerStateResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/PowerState"
                }
            ]
        },
        "PowerControlResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "IntegratedPowerValue": {
            "type": "object",
            "required": [
                "integratedpowervalue"
            ],
            "properties": {
                "integratedpowervalue": {
                    "type": "array",
                    "title": "積算電力量",
                    "description": "サイズが24のnumberの配列。各値は積算電力量を表す実数。単位はWh。時間順に格納されているため、最初の要素は24時間前のもの。<br><br>例: リクエストで date=2015-08-24T15:14:00+0900 を指定した場合、0から23までの各インデックスに対応する時間帯は下記のとおり。<br>0 : 2015-08-23T15:00 ~ 15:59<br> :<br>23 :2015-08-24T14:00 ~ 14:59",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 24,
                    "maxItems": 24
                }
            }
        },
        "IntegratedPowerValueResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/IntegratedPowerValue"
                }
            ]
        },
        "InstantaneousPowerValue": {
            "type": "object",
            "required": [
                "instantaneouspowervalue"
            ],
            "properties": {
                "instantaneouspowervalue": {
                    "type": "number",
                    "title": "瞬間電力量",
                    "description": "瞬間電力量を表す実数。単位はW。"
                }
            }
        },
        "InstantaneousPowerValueResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/InstantaneousPowerValue"
                }
            ]
        },
        "CommonResponse": {
            "type": "object",
            "required": [
                "result",
                "product",
                "version"
            ],
            "properties": {
                "result": {
                    "type": "integer",
                    "title": "処理結果",
                    "description": "0: 正常応答<br>0以外: 異常応答"
                },
                "product": {
                    "type": "string",
                    "title": "DeviceConnectシステムの名前",
                    "description": ""
                },
                "version": {
                    "type": "string",
                    "title": "DeviceConnectシステムのバージョン名",
                    "description": ""
                },
                "hmac": {
                    "type": "string",
                    "title": "レスポンスに対する署名",
                    "description": "アプリケーション側から事前にHMACキーを共有されていた場合は必須。"
                }
            }
        }
    }
}